export const DATA_CHECKED_ON = '2026-07-27';

const dated = (record) => Object.freeze({ ...record, checkedOn: DATA_CHECKED_ON });

export const aiTools = Object.freeze({
    bolt: dated({
        name: 'Bolt.new', icon: '\u26A1', type: 'App Builder',
        output: 'Exported web application source; inspect the generated package manifest and framework',
        pricing: 'Free and paid usage-credit plans; verify live allowances and overages',
        workflow: 'Browser builder with native publishing and code export paths',
        desc: 'Browser-based application builder. Treat its generated dependencies, environment variables, and deployment settings as project-specific.',
        hostName: 'Bolt hosting or an exported-code host',
        hostDesc: 'Use native publishing for the shortest path, or export and deploy to a host compatible with the generated runtime.',
        dbName: 'Project-selected database', dbDesc: 'Inspect the generated project and current Bolt integrations before choosing a production database.',
        rationale: 'Choose by the actual exported framework, server requirements, secrets, and data layer—not by a generic tool label.',
        hostIcon: '\u26A1', dbIcon: '\uD83D\uDDC4\uFE0F',
        nativeDeploy: 'Bolt provides publishing options; verify current custom-domain, usage, and production limits.',
        source: 'https://bolt.new/pricing',
    }),
    v0: dated({
        name: 'v0', icon: '\u25B2', type: 'UI / App Generator',
        output: 'Web application code; commonly aligned with React and Next.js workflows',
        pricing: 'Credit-based free and paid plans; verify current credits and team terms',
        workflow: 'Generate, review, connect a repository, then deploy to a compatible web host',
        desc: 'Vercel\'s web application generator. Inspect server-side features and integrations before treating a prototype as production-ready.',
        hostName: 'Vercel or a compatible web host', hostDesc: 'Vercel is the native path; exported code can be evaluated against other compatible hosts.',
        dbName: 'Project-selected database', dbDesc: 'Database requirements depend on the generated application and integrations.',
        rationale: 'The deployment target should match the generated repository, runtime, and commercial-use requirements.',
        hostIcon: '\u25B2', dbIcon: '\uD83D\uDDC4\uFE0F', nativeDeploy: 'A Vercel workflow is available; verify plan and commercial-use terms.',
        source: 'https://v0.app/pricing',
    }),
    cursor: dated({
        name: 'Cursor', icon: '\uD83D\uDDA5\uFE0F', type: 'AI IDE',
        output: 'Any repository supported by the project toolchain',
        pricing: 'Free and paid plans; verify current included usage and model access',
        workflow: 'Local repository workflow; deploy according to the application runtime',
        desc: 'AI-assisted code editor. It does not determine the application\'s production host.',
        hostName: 'Match the runtime', hostDesc: 'Use the package manifest, framework configuration, Dockerfile, and persistence requirements to select a host.',
        dbName: 'Match the application', dbDesc: 'Choose a managed database only after reviewing schema, migration, backup, and connection requirements.',
        rationale: 'Cursor can edit many stacks; the repository—not the editor—determines deployment compatibility.',
        hostIcon: '\uD83D\uDEA2', dbIcon: '\uD83D\uDDC4\uFE0F', nativeDeploy: null,
        source: 'https://cursor.com/pricing',
    }),
    lovable: dated({
        name: 'Lovable', icon: '\uD83D\uDC9C', type: 'App Builder',
        output: 'Web application source; inspect current export and integration behavior',
        pricing: 'Free and paid credit plans; verify current allowances and workspace terms',
        workflow: 'Native publish path or exported repository workflow',
        desc: 'Browser-based application builder with managed publishing and integrations. Production behavior depends on the generated project and enabled services.',
        hostName: 'Lovable publishing or exported-code host', hostDesc: 'Use the native path for convenience or export and validate the repository on a compatible platform.',
        dbName: 'Current project integration', dbDesc: 'Inspect the connected backend, access controls, migrations, and backups before launch.',
        rationale: 'Validate generated access controls and environment separation before exposing real user data.',
        hostIcon: '\uD83D\uDC9C', dbIcon: '\uD83D\uDD25', nativeDeploy: 'Native publishing is available; verify current plan, domain, and environment behavior.',
        source: 'https://lovable.dev/pricing',
    }),
    windsurf: dated({
        name: 'Windsurf', icon: '\uD83C\uDFC4', type: 'AI IDE',
        output: 'Any repository supported by the project toolchain',
        pricing: 'Free and paid plans; verify current usage allowances',
        workflow: 'Local repository workflow; deploy according to the generated runtime',
        desc: 'AI-assisted development environment. Hosting compatibility follows the repository and infrastructure configuration.',
        hostName: 'Match the runtime', hostDesc: 'Inspect framework, build, process, storage, and network requirements before choosing a platform.',
        dbName: 'Match the application', dbDesc: 'Select and secure the database based on project requirements, not editor defaults.',
        rationale: 'The generated code and runtime contract are the deployment evidence.',
        hostIcon: '\uD83D\uDEA2', dbIcon: '\uD83D\uDDC4\uFE0F', nativeDeploy: null,
        source: 'https://windsurf.com/pricing',
    }),
    replit: dated({
        name: 'Replit', icon: '\uD83D\uDD04', type: 'Cloud IDE + Host',
        output: 'Hosted application or exported repository',
        pricing: 'Free and paid credit-based plans; verify current deployment charges',
        workflow: 'Integrated build and deployment with optional repository export',
        desc: 'Cloud development environment with integrated deployment products. Product and usage charges vary by deployment type.',
        hostName: 'Replit Deployments or exported-code host', hostDesc: 'Choose the deployment type by uptime, scaling, persistence, and budget requirements.',
        dbName: 'Project-selected storage', dbDesc: 'Confirm whether the project uses managed SQL, object storage, or platform-specific data services.',
        rationale: 'Integrated deployment is convenient; test portability and document all attached services before launch.',
        hostIcon: '\uD83D\uDD04', dbIcon: '\uD83D\uDCBE', nativeDeploy: 'Integrated deployment options are available; verify current products and billing.',
        source: 'https://replit.com/pricing',
    }),
    claude: dated({
        name: 'Claude Code', icon: '\uD83E\uDDE0', type: 'AI Coding Agent',
        output: 'Any repository supported by the project toolchain',
        pricing: 'Available through current Anthropic subscription and API options; verify usage terms',
        workflow: 'Terminal/repository workflow; deploy according to the application runtime',
        desc: 'Repository-aware coding agent. It can assist with deployment files but does not make an application production-safe automatically.',
        hostName: 'Match the runtime', hostDesc: 'Use the repository\'s tested build and runtime contract to select a provider.',
        dbName: 'Match the application', dbDesc: 'Review schema, credentials, migrations, network access, backups, and recovery.',
        rationale: 'Require tests, staged-file review, secret scanning, and a rollback path before deployment.',
        hostIcon: '\uD83D\uDEA2', dbIcon: '\uD83D\uDDC4\uFE0F', nativeDeploy: null,
        source: 'https://www.anthropic.com/pricing',
    }),
    base44: dated({
        name: 'Base44', icon: '\uD83D\uDFE6', type: 'Managed App Builder',
        output: 'Managed web application with current export options varying by plan',
        pricing: 'Credit-based plans; verify message, integration, and service charges',
        workflow: 'Managed build and hosting path; validate export and service dependencies',
        desc: 'Managed application builder with usage credits and third-party service considerations.',
        hostName: 'Base44 managed hosting', hostDesc: 'Treat portability, export, custom-domain, and attached-service behavior as current-plan questions.',
        dbName: 'Base44 managed data layer', dbDesc: 'Verify access controls, export, backup, and migration options before storing production data.',
        rationale: 'Best for users accepting a managed platform; portability-sensitive projects need an export test first.',
        hostIcon: '\uD83D\uDFE6', dbIcon: '\uD83D\uDDC4\uFE0F', nativeDeploy: 'Managed publishing is part of the platform; verify current limits and ownership terms.',
        source: 'https://base44.com/pricing',
    }),
    newly: dated({
        name: 'Newly (formerly Natively)', icon: '\uD83D\uDCF1', type: 'Mobile Builder',
        output: 'Native iOS and Android project workflow',
        pricing: 'Verify current Newly plans and build allowances',
        workflow: 'Generate, review, sign, test, and submit through mobile distribution workflows',
        desc: 'The former Natively pricing route redirects to Newly. Old Natively price and feature claims are no longer treated as current facts.',
        hostName: 'App Store / Google Play', hostDesc: 'Native apps are distributed through signed store workflows rather than web hosting.',
        dbName: 'Project-selected backend', dbDesc: 'Verify the generated backend, authentication, privacy, and data-deletion behavior.',
        rationale: 'Review current store rules and test signed release builds; builder choice does not guarantee approval.',
        hostIcon: '\uD83D\uDCF1', dbIcon: '\uD83D\uDD25', nativeDeploy: 'Follow the current Newly build flow plus Apple and Google submission requirements.',
        source: 'https://newly.app/pricing',
    }),
    emergent: dated({
        name: 'Emergent', icon: '\uD83C\uDF00', type: 'Agent Platform',
        output: 'Managed full-stack application or current export path',
        pricing: 'Live plan details are dynamically rendered; verify before purchase',
        workflow: 'Managed generation and deployment; inspect current export and attached services',
        desc: 'Managed agent platform. Avoid publishing static plan limits that cannot be reproduced from its live pricing page.',
        hostName: 'Emergent managed hosting', hostDesc: 'Verify custom-domain, scaling, export, and service limits in the current product.',
        dbName: 'Current managed integration', dbDesc: 'Review access controls, portability, backups, and data lifecycle.',
        rationale: 'Use only after validating the current plan and an export or recovery path for the specific application.',
        hostIcon: '\uD83C\uDF00', dbIcon: '\uD83D\uDDC4\uFE0F', nativeDeploy: 'Managed deployment is available; current details should be checked in-product.',
        source: 'https://app.emergent.sh/pricing',
    }),
});

export const toolsLandscape = Object.freeze(Object.values(aiTools).map((tool) => Object.freeze({
    name: tool.name,
    type: tool.type,
    output: tool.output,
    pricing: tool.pricing,
    workflow: tool.workflow,
    checkedOn: tool.checkedOn,
    source: tool.source,
})));

export const hostingPlatforms = Object.freeze([
    dated({ name: 'Vercel', type: 'frontend', bestFor: 'Next.js and compatible web applications', free: 'Hobby is $0; current usage limits apply', commercial: 'Hobby is for non-commercial use', lifecycle: 'Function and compute behavior varies by product and configuration', deployment: 'Git / CLI', db: 'External or marketplace integration', docker: 'No general Docker deployment', note: 'Pro is listed at $20/month with usage credit; recheck live limits before quoting quotas.', url: 'https://vercel.com/pricing', source: 'https://vercel.com/pricing' }),
    dated({ name: 'Netlify', type: 'frontend', bestFor: 'Static sites and supported web frameworks', free: 'Free plan uses a monthly credit allowance', commercial: 'Commercial use subject to current terms', lifecycle: 'Functions and edge products have separate limits', deployment: 'Git / CLI', db: 'External integrations', docker: 'No general Docker deployment', note: 'The previous bandwidth/build-minute bundle is obsolete; use the current credit model.', url: 'https://www.netlify.com/pricing/', source: 'https://www.netlify.com/pricing/' }),
    dated({ name: 'Cloudflare Pages', type: 'frontend', bestFor: 'Static assets and Workers-integrated applications', free: 'Static asset delivery and build limits differ from Workers usage', commercial: 'Commercial use subject to current terms', lifecycle: 'Pages Functions are billed and limited as Workers', deployment: 'Git / Wrangler', db: 'D1, KV, R2, or external', docker: 'No', note: 'Do not describe all Pages/Workers requests as universally unlimited.', url: 'https://developers.cloudflare.com/pages/functions/pricing/', source: 'https://developers.cloudflare.com/pages/functions/pricing/' }),
    dated({ name: 'Railway', type: 'fullstack', bestFor: 'Containerized and language-runtime services', free: 'Trial and plan-credit terms vary; check current plans', commercial: 'Yes, subject to current terms', lifecycle: 'Services run according to configuration, resources, and account limits', deployment: 'Git / Dockerfile / CLI', db: 'Managed templates and external services', docker: 'Yes', note: 'Usage is resource-based; do not equate a subscription fee with included compute.', url: 'https://railway.com?referralCode=UmzYpw', affiliate: true, relationship: 'affiliate', source: 'https://docs.railway.com/pricing/plans' }),
    dated({ name: 'Render', type: 'fullstack', bestFor: 'Web services, workers, static sites, and managed data services', free: 'Selected free resources exist with documented limitations', commercial: 'Yes, subject to current terms', lifecycle: 'Free-resource suspension and retention rules are product-specific', deployment: 'Git / Docker', db: 'Managed Postgres and other products', docker: 'Yes', note: 'Read the current free-resource limitations before relying on persistence or uptime.', url: 'https://render.com/docs/free', source: 'https://render.com/docs/free' }),
    dated({ name: 'Fly.io', type: 'fullstack', bestFor: 'VM-based applications requiring region control', free: 'No general-purpose free allowance is promised', commercial: 'Yes, subject to current terms', lifecycle: 'Machine autostop/autostart is configurable', deployment: 'CLI / container image', db: 'Self-managed or provider products', docker: 'Container image workflow', note: 'Compute, volumes, snapshots, network, and support can be separate charges.', url: 'https://fly.io/docs/about/pricing/', source: 'https://fly.io/docs/about/pricing/' }),
    dated({ name: 'DigitalOcean App Platform', type: 'fullstack', bestFor: 'Managed application and static-site deployments', free: 'Free static-site allowance; dynamic components are paid', commercial: 'Yes, subject to current terms', lifecycle: 'Behavior depends on component type and selected plan', deployment: 'Git / container image', db: 'DigitalOcean managed databases or external', docker: 'Container image supported', note: 'Direct referral link confirmed; use the pricing documentation for current component rates.', url: 'https://m.do.co/c/0ac1da4ad477', affiliate: true, relationship: 'direct_referral', source: 'https://docs.digitalocean.com/products/app-platform/details/pricing/' }),
    dated({ name: 'Heroku', type: 'fullstack', bestFor: 'Dyno-based application workflows', free: 'No general free dyno tier', commercial: 'Yes, subject to current terms', lifecycle: 'Dyno behavior depends on current product and plan', deployment: 'Git / container registry', db: 'Paid data products and add-ons', docker: 'Container registry supported', note: 'Dynos, data products, AI products, and add-ons are priced separately.', url: 'https://www.heroku.com/pricing/', source: 'https://www.heroku.com/pricing/' }),
]);

export const registrars = Object.freeze([
    dated({ name: 'Cloudflare Registrar', pricing: 'At-cost registration and renewal; check the live TLD quote', privacy: 'WHOIS redaction where registry rules allow', dns: 'Cloudflare DNS required', note: 'Strong long-term pricing policy; requires using Cloudflare nameservers.', url: 'https://www.cloudflare.com/products/registrar/', source: 'https://www.cloudflare.com/products/registrar/' }),
    dated({ name: 'Porkbun', pricing: 'Live registration, renewal, and transfer table', privacy: 'Privacy service availability varies by TLD', dns: 'Included DNS tools', note: 'Compare the exact TLD across registration, renewal, and transfer columns.', url: 'https://porkbun.com/products/domains', source: 'https://porkbun.com/products/domains' }),
    dated({ name: 'Namecheap', pricing: 'Live first-year, renewal, and transfer pricing varies by TLD', privacy: 'Check the exact TLD and current privacy terms', dns: 'Included DNS tools', note: 'Confirmed Impact affiliate link; use only in a domain-intent context.', url: 'https://namecheap.pxf.io/rEErVj', affiliate: true, relationship: 'affiliate', source: 'https://www.namecheap.com/domains/registration/gtld/' }),
    dated({ name: 'Hover', pricing: 'Live registration and renewal quote varies by TLD', privacy: 'Check current privacy inclusion and TLD rules', dns: 'Included DNS tools', note: 'Simple registrar workflow; compare the exact TLD renewal cost.', url: 'https://www.hover.com/domains', source: 'https://www.hover.com/domains' }),
]);

export const affiliatePrograms = Object.freeze([
    dated({
        name: 'DigitalOcean', verified: true, status: 'Active direct referral',
        relationship: 'Direct referral', commission: 'Account-dashboard referral terms', cookie: 'Not published',
        payout: 'Referral reward or credit per dashboard', network: 'DigitalOcean Referral Program',
        offer: 'Current landing-page offer applies', url: 'https://m.do.co/c/0ac1da4ad477',
        notes: 'Confirmed direct DigitalOcean referral. It is not represented as an Awin or CJ cash-affiliate account.',
        source: 'https://www.digitalocean.com/referral-program/', chartValue: null,
    }),
    dated({
        name: 'Railway', verified: true, status: 'Active affiliate',
        relationship: 'Affiliate', commission: '15% recurring for 12 months', cookie: '12-month attribution window',
        payout: 'Check the current account dashboard', network: 'Railway direct',
        offer: 'Current landing-page offer applies', url: 'https://railway.com?referralCode=UmzYpw',
        notes: 'Confirmed Railway affiliate link. Current public terms were checked on the date shown.',
        source: 'https://railway.com/affiliate-program', chartValue: null,
    }),
    dated({
        name: 'Hostinger', verified: true, status: 'Active direct referral',
        relationship: 'Direct referral', commission: 'Account-dashboard terms', cookie: 'Check current dashboard terms',
        payout: 'Check current dashboard terms', network: 'Hostinger direct',
        offer: 'Current referral landing-page offer applies', url: 'https://www.hostinger.com?REFERRALCODE=SNPULRICHICN',
        notes: 'Confirmed direct Hostinger link. Use for VPS/control-plane or conventional hosting intent, not GPU inference.',
        source: 'https://www.hostinger.com/affiliates', chartValue: null,
    }),
    dated({
        name: 'Bluehost', verified: true, status: 'Active Impact affiliate',
        relationship: 'Affiliate', commission: 'Impact dashboard terms', cookie: 'Check current dashboard terms',
        payout: 'Check current dashboard terms', network: 'Impact',
        offer: 'Current landing-page offer applies', url: 'https://bluehost.sjv.io/9VVDN4',
        notes: 'Use only for WordPress or conventional hosting intent; it is not a default app-platform recommendation.',
        source: 'https://www.bluehost.com/affiliates', chartValue: null,
    }),
    dated({
        name: 'Namecheap', verified: true, status: 'Active Impact affiliate',
        relationship: 'Affiliate', commission: 'Impact dashboard terms', cookie: 'Check current dashboard terms',
        payout: 'Check current dashboard terms', network: 'Impact',
        offer: 'Current landing-page offer applies', url: 'https://namecheap.pxf.io/rEErVj',
        notes: 'Confirmed Impact affiliate link. Use only in domain-registration and DNS workflows.',
        source: 'https://www.namecheap.com/affiliates/', chartValue: null,
    }),
    dated({
        name: 'Liquid Web', verified: false, status: 'Not approved',
        relationship: 'Editorial only', commission: 'No active relationship', cookie: 'Not applicable',
        payout: 'Not applicable', network: 'Application denied or pending', offer: 'Editorial coverage only',
        notes: 'No monetized link is published because the application has not been approved.',
        source: null, chartValue: null,
    }),
    dated({
        name: 'Vultr', verified: false, status: 'Not approved',
        relationship: 'Editorial only', commission: 'No active relationship', cookie: 'Not applicable',
        payout: 'Not applicable', network: 'No approved publisher relationship', offer: 'Editorial coverage only',
        notes: 'No monetized link is published because there is no approved publisher relationship.',
        source: null, chartValue: null,
    }),
]);
